# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/sketchstar',
                'doc_host': 'https://RensDimmendaal.github.io',
                'git_url': 'https://github.com/RensDimmendaal/sketchstar',
                'lib_path': 'sketchstar'},
  'syms': { 'sketchstar.core': { 'sketchstar.core.create_animation_async': ('core.html#create_animation_async', 'sketchstar/core.py'),
                                 'sketchstar.core.get_gif': ('core.html#get_gif', 'sketchstar/core.py'),
                                 'sketchstar.core.get_session_gif': ('core.html#get_session_gif', 'sketchstar/core.py'),
                                 'sketchstar.core.get_status': ('core.html#get_status', 'sketchstar/core.py'),
                                 'sketchstar.core.index': ('core.html#index', 'sketchstar/core.py'),
                                 'sketchstar.core.submit_drawing': ('core.html#submit_drawing', 'sketchstar/core.py')}}}
